apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: app1-tg-config
  namespace: default
spec:
  targetReference:
    name: app1
  defaultConfiguration:
    targetType: ip
---
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: app2-tg-config
  namespace: default
spec:
  targetReference:
    name: app2
  defaultConfiguration:
    targetType: ip