apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-1
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: sg-09b9c10bbccc4ee84
    alb.ingress.kubernetes.io/subnets: subnet-03014d2c59d25004d, subnet-092620b01b8d51244

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-proxy-service
                port:
                  number: 80